INSERT INTO USERS VALUES (1, 'SDD', 'Stephane', 'David');
INSERT INTO USERS VALUES (2, 'TBO', 'Tristan', 'Bouju');
INSERT INTO USERS VALUES (3, 'VVE', 'Valerie', 'Vega');
INSERT INTO USERS VALUES (4, 'DRO', 'Daniel', 'Roina');
INSERT INTO USERS VALUES (666, 'TO', 'BE', 'DELETED');
ALTER SEQUENCE SEQ_USERS RESTART WITH 5;

INSERT INTO SPRINTS VALUES ('SPR-0', '0', DATE '2015-12-01', DATE '2015-12-31', 'sprint exploratoire', 21, 21);
INSERT INTO SPRINTS VALUES ('SPR-1', '1', DATE '2016-01-01', DATE '2016-01-31', 'sprint1 goal', 13, 11);
INSERT INTO SPRINTS VALUES ('SPR-2', 'current', DATEADD('DAY', -5, SYSDATE), DATEADD('DAY', 7, SYSDATE), 'sprint2 goal', 44, 23);
INSERT INTO SPRINTS VALUES ('TO_BE_DELETED', 'TO_BE_DELETED', DATE '2000-01-01', DATE '2000-12-31', NULL, 100, 0);

INSERT INTO SPRINT_DAYS VALUES (DATE '2015-12-31', 666);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-01', 0);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-04', 0);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-05', 5);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-06', 5);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-08', 6);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-01-31', 13);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-07-14', 123);
INSERT INTO SPRINT_DAYS VALUES (DATE '2016-08-15', 456);

INSERT INTO ACTIVITIES VALUES ('ACT-01', 'US',   '1',  'activity 1', 'DRAFT');
INSERT INTO ACTIVITIES VALUES ('ACT-02', 'US',   '2',  'activity longue 2', 'READY');
INSERT INTO ACTIVITIES VALUES ('ACT-03', 'US',   '3',  'activity 3', 'PENDING');
INSERT INTO ACTIVITIES VALUES ('ACT-04', 'US',   '4',  'activity 4', 'DONE');
INSERT INTO ACTIVITIES VALUES ('ACT-05', 'US',   '5',  'activity longue 5', 'DRAFT');
INSERT INTO ACTIVITIES VALUES ('ACT-06', 'US',   '6',  'activity 6', 'READY');
INSERT INTO ACTIVITIES VALUES ('ACT-07', 'TASK', '7',  'activity 7', 'PENDING');
INSERT INTO ACTIVITIES VALUES ('ACT-08', 'TASK', '8',  'activity longue 8', 'DONE');
INSERT INTO ACTIVITIES VALUES ('ACT-09', 'TASK', '9',  'activity 9', 'DRAFT');
INSERT INTO ACTIVITIES VALUES ('ACT-10', 'TASK', '10', 'activity 10', 'READY');

INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (1, 'user story 1', 'DRAFT',   SYSDATE, 100, 10);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (2, 'user story 2', 'READY',   SYSDATE, 200, 20);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (3, 'user story 3', 'PENDING', SYSDATE, 300, 30);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (4, 'user story 4', 'DONE',    SYSDATE, 400, 40);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (5, 'user story 5', 'DRAFT',   SYSDATE, 500, 50);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (6, 'user story 6', 'READY',   SYSDATE, 600, 60);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (7, 'user story 7', 'PENDING', SYSDATE, 700, 70);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (8, 'user story 8', 'DONE',    SYSDATE, 800, 80);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (9, 'to be updated', 'DRAFT',  SYSDATE, 100, 100);
INSERT INTO STORIES(ID,DESCRIPTION,STATUS,LAST_UPDATE,CONTRIBUTION,ESTIMATE) VALUES (666, 'to be deleted', 'DRAFT', SYSDATE, 0, 1000);
ALTER SEQUENCE SEQ_STORIES RESTART WITH 10;
