INSERT INTO USERS VALUES ('01', 'SDD', 'Stephane', 'David');
INSERT INTO USERS VALUES ('02', 'BBB', 'Babane', '');
INSERT INTO USERS VALUES ('03', 'TBO', 'Tristan', 'Bouju');
INSERT INTO USERS VALUES ('TO_BE_DELETED', 'TO', 'BE', 'DELETED');

INSERT INTO SPRINTS VALUES ('SPR-1', '1', DATE '2016-01-01', DATE '2016-01-31');
INSERT INTO SPRINTS VALUES ('SPR-2', 'current', DATEADD('DAY', -5, SYSDATE), DATEADD('DAY', 5, SYSDATE));
INSERT INTO SPRINTS VALUES ('TO_BE_DELETED', 'TO_BE_DELETED', DATE '2000-01-01', DATE '2000-12-31');
