TRUNCATE TABLE USERS;
ALTER SEQUENCE SEQ_USERS RESTART WITH 1;

TRUNCATE TABLE SPRINTS;

TRUNCATE TABLE SPRINT_DAYS;

TRUNCATE TABLE ACTIVITIES;

TRUNCATE TABLE STORIES;
ALTER SEQUENCE SEQ_STORIES RESTART WITH 1;
